# yaml
name: Compile Java Backend

on: [push, pull_request]

concurrency:
  group: compile-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-backend:
    name: Compile Backend Code
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compile with Maven
        run: mvn -B -ntp -DskipTests compile